//! The menu-bar icon and its state.
//!
//! The icon is the application's primary surface: for a healthy installation it
//! is the *only* thing the user ever sees. It carries state through distinct
//! glyphs rather than colour alone, and its tooltip repeats that state in words
//! so it survives greyscale, high-contrast, and VoiceOver (spec §33).

use secretctl_protocol::UiProtectionState;
use tauri::image::Image;
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::AppHandle;

pub const TRAY_ID: &str = "secretctl";

/// The template images generated by `desktop/icons/generate.py`, embedded so the
/// icon is available before any resource directory is resolved.
fn icon_bytes(state: UiProtectionState) -> &'static [u8] {
    match state {
        UiProtectionState::Protected => include_bytes!("../../icons/tray/protected@2x.png"),
        UiProtectionState::ApprovalRequired => {
            include_bytes!("../../icons/tray/approval_required@2x.png")
        }
        UiProtectionState::SensitiveOperation => {
            include_bytes!("../../icons/tray/sensitive_operation@2x.png")
        }
        UiProtectionState::Completed => include_bytes!("../../icons/tray/completed@2x.png"),
        UiProtectionState::Blocked => include_bytes!("../../icons/tray/blocked@2x.png"),
        UiProtectionState::ProtectionInterrupted => {
            include_bytes!("../../icons/tray/protection_interrupted@2x.png")
        }
        // An unverifiable outcome is shown with the interrupted glyph: in both
        // cases the honest statement is that secretctl cannot confirm the state.
        UiProtectionState::OutcomeUncertain => {
            include_bytes!("../../icons/tray/protection_interrupted@2x.png")
        }
        UiProtectionState::Disconnected => include_bytes!("../../icons/tray/disconnected@2x.png"),
    }
}

/// The words shown in the tooltip. Kept plain: no error codes, no jargon.
pub fn state_label(state: UiProtectionState) -> &'static str {
    match state {
        UiProtectionState::Protected => "Protected",
        UiProtectionState::ApprovalRequired => "Approval required",
        UiProtectionState::SensitiveOperation => "Sensitive operation in progress",
        UiProtectionState::Completed => "Completed",
        UiProtectionState::Blocked => "Blocked",
        UiProtectionState::ProtectionInterrupted => "Protection interrupted",
        UiProtectionState::OutcomeUncertain => "Outcome could not be verified",
        UiProtectionState::Disconnected => "secretctl unavailable",
    }
}

pub fn build(app: &AppHandle) -> tauri::Result<TrayIcon> {
    // The right-click menu stays minimal. Everything substantive lives in the
    // popover; this is an escape hatch, not a second navigation surface.
    let activity = MenuItem::with_id(app, "activity", "Activity…", true, None::<&str>)?;
    let grants = MenuItem::with_id(app, "grants", "Standing authorizations…", true, None::<&str>)?;
    let settings = MenuItem::with_id(app, "settings", "Settings…", true, None::<&str>)?;
    let quit = MenuItem::with_id(app, "quit", "Quit secretctl", true, None::<&str>)?;
    let menu = Menu::with_items(
        app,
        &[
            &activity,
            &grants,
            &settings,
            &PredefinedMenuItem::separator(app)?,
            &quit,
        ],
    )?;

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(Image::from_bytes(icon_bytes(UiProtectionState::Disconnected))?)
        .icon_as_template(true)
        .tooltip(format!(
            "secretctl — {}",
            state_label(UiProtectionState::Disconnected)
        ))
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| {
            let section = match event.id.as_ref() {
                "activity" => "activity",
                "grants" => "grants",
                "settings" => "settings",
                "quit" => {
                    app.exit(0);
                    return;
                }
                _ => return,
            };
            if let Err(error) = crate::windows::open_manage(app, section) {
                tracing::error!(%error, "could not open management window");
            }
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                rect,
                ..
            } = event
            {
                let position = rect.position.to_physical::<f64>(1.0);
                let size = rect.size.to_physical::<f64>(1.0);
                let anchor = Some((position.x, position.y + size.height, size.width));
                if let Err(error) = crate::windows::toggle_popover(tray.app_handle(), anchor) {
                    tracing::error!(%error, "could not open popover");
                }
            }
        })
        .build(app)
}

/// Apply a new protection state to the icon.
///
/// Called only from the watcher, which derives the state from the daemon. The
/// UI never sets it from a local assumption — an icon that claimed "Protected"
/// while the daemon was unreachable would be a lie in exactly the situation
/// where the truth matters most.
pub fn apply_state(app: &AppHandle, state: UiProtectionState) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    if let Ok(image) = Image::from_bytes(icon_bytes(state)) {
        let _ = tray.set_icon(Some(image));
        let _ = tray.set_icon_as_template(true);
    }
    let _ = tray.set_tooltip(Some(format!("secretctl — {}", state_label(state))));
}
