[package]
name = "secretctl-native-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
secretctl-domain = { workspace = true }
secretctl-protocol = { workspace = true }
secretctl-crypto = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
