[package]
name = "secretctl-provider-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
secretctl-crypto = { workspace = true }
secretctl-providers = { workspace = true }
async-trait = { workspace = true }
