#!/usr/bin/env python3
"""Extract localizable strings into Resources/en.lproj/Localizable.strings.

SwiftUI localizes `Text("…")`, `Button("…")` and friends automatically: the
literal *is* the key. So the base catalogue is a list of those literals plus
every `String(localized:)` in the kit, and translating the app means dropping a
`<lang>.lproj/Localizable.strings` beside the English one with the same keys.

Two things this deliberately does not do:

* `Text(verbatim:)` is never extracted. That is the agent-supplied reason, and
  it must not pass through a translation table — a translator is not in a
  position to vouch for attacker-controlled text, and a stale entry could
  silently rewrite it.
* Machine tokens are never extracted. Error symbols like `EPOCH_INVALIDATED`
  are protocol surface, not prose.

Interpolations become printf placeholders, matching what SwiftUI's own
extractor produces. The type is inferred, and anything ambiguous is reported so
a human can check it rather than being guessed at silently.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCES = ROOT / "Sources"
OUTPUT = ROOT / "Resources" / "en.lproj" / "Localizable.strings"

# Views: SwiftUI treats the first string literal of these as a LocalizedStringKey.
VIEW_CALLS = r"(?:Text|Button|Toggle|Picker|Label|SectionHeading\(title:|" \
             r"\.navigationTitle|\.accessibilityLabel|\.accessibilityHint|" \
             r"\.accessibilityValue|\.help|\.confirmationDialog)"
VIEW_PATTERN = re.compile(VIEW_CALLS + r'\s*\(\s*"((?:[^"\\]|\\.)*)"')
KIT_PATTERN = re.compile(r'String\(localized:\s*"((?:[^"\\]|\\.)*)"')
VERBATIM = re.compile(r'Text\(\s*verbatim:')

# Interpolated expressions that are plainly a count rather than a name.
NUMERIC_HINT = re.compile(
    r"count|\.count\b|Limit|days|ttl|sequence|pending|Approvals|Connected|Grants|Enrolled|Active"
)


def placeholderise(literal: str) -> tuple[str, list[str]]:
    """Turn `\\(expr)` into %@ / %lld, reporting anything ambiguous."""
    ambiguous: list[str] = []

    def replace(match: re.Match[str]) -> str:
        expression = match.group(1)
        if NUMERIC_HINT.search(expression):
            return "%lld"
        # Not obviously numeric: treat as a string, and say so.
        if not re.fullmatch(r"[A-Za-z_][\w.]*", expression):
            ambiguous.append(expression)
        return "%@"

    return re.sub(r"\\\(([^()]*(?:\([^()]*\))?[^()]*)\)", replace, literal), ambiguous


def main() -> int:
    found: dict[str, set[str]] = {}
    ambiguities: list[tuple[str, str]] = []

    for path in sorted(SOURCES.rglob("*.swift")):
        text = path.read_text(encoding="utf-8")
        for line in text.splitlines():
            if VERBATIM.search(line):
                continue
            for pattern in (VIEW_PATTERN, KIT_PATTERN):
                for raw in pattern.findall(line):
                    if not raw.strip():
                        continue
                    # Machine tokens and format-only strings are not prose.
                    if re.fullmatch(r"[A-Z0-9_]+", raw):
                        continue
                    key, ambiguous = placeholderise(raw)
                    found.setdefault(key, set()).add(path.name)
                    ambiguities.extend((key, item) for item in ambiguous)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as handle:
        handle.write(
            "/* secretctl — base localization.\n"
            "   Generated by Tools/localize/extract.py. Do not edit by hand.\n\n"
            "   To translate: copy this file to <lang>.lproj/Localizable.strings and\n"
            "   replace the values, never the keys. Placeholders must keep their order;\n"
            "   use %1$@ style indices where a language needs to reorder them. */\n\n"
        )
        for key in sorted(found):
            sources = ", ".join(sorted(found[key]))
            escaped = key.replace("\\", "\\\\").replace('"', '\\"')
            handle.write(f"/* {sources} */\n\"{escaped}\" = \"{escaped}\";\n\n")

    print(f"{len(found)} strings -> {OUTPUT.relative_to(ROOT)}")
    if ambiguities:
        print("\nPlaceholder types worth checking by hand:")
        for key, expression in sorted(set(ambiguities)):
            print(f"  {expression!r} in {key!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
