import CryptoKit
import Foundation
import Testing
@testable import SecretctlKit

/// The Swift client reimplements the broker handshake with CryptoKit instead of
/// linking the Rust crates. These tests are the thing that stops the two
/// implementations drifting: every vector is generated by
/// `macos/Tools/handshake-vectors` from the real `secretctl-crypto` code.
///
/// A failure here means the menu-bar app would be rejected at `session.
/// authenticate` — or, worse, would agree on a key the daemon did not intend.
struct CrossLanguageCryptoTests {
    static let vectors: [String: Any] = {
        let url = Bundle.module.url(forResource: "handshake", withExtension: "json", subdirectory: "Vectors")
            ?? Bundle.module.url(forResource: "handshake", withExtension: "json")!
        let data = try! Data(contentsOf: url)
        return try! JSONSerialization.jsonObject(with: data) as! [String: Any]
    }()

    static func group(_ name: String) -> [String: Any] {
        vectors[name] as! [String: Any]
    }

    static func hex(_ string: String) -> Data {
        var bytes = [UInt8]()
        var index = string.startIndex
        while index < string.endIndex {
            let next = string.index(index, offsetBy: 2)
            bytes.append(UInt8(string[index..<next], radix: 16)!)
            index = next
        }
        return Data(bytes)
    }

    @Test("Length-prefixed context digest matches the Rust implementation")
    func contextDigestMatchesRust() {
        let group = Self.group("context_digest")
        let components = (group["components"] as! [String]).map { Data($0.utf8) }
        let expected = Self.hex(group["digest_hex"] as! String)
        #expect(ContextDigest.compute(components) == expected)
    }

    @Test("An empty component still contributes its length prefix")
    func emptyComponentIsNotSkipped() {
        // Without the length prefix these two would collide, which is exactly
        // the transcript-confusion the prefix exists to prevent.
        let joined = ContextDigest.compute([Data("ab".utf8), Data("c".utf8)])
        let split = ContextDigest.compute([Data("a".utf8), Data("bc".utf8)])
        #expect(joined != split)
    }

    @Test("The signed session.authenticate transcript matches the Rust implementation")
    func sessionAuthTranscriptMatchesRust() {
        let group = Self.group("session_auth_transcript")
        let digest = ContextDigest.compute([
            Data("secretctl-session-auth-v1".utf8),
            Data((group["protocol_version"] as! String).utf8),
            Data((group["role"] as! String).utf8),
            Data((group["principal_id"] as! String).utf8),
            Data((group["client_nonce"] as! String).utf8),
            Data((group["server_nonce"] as! String).utf8),
            Self.hex(group["server_ephemeral_public_hex"] as! String),
            Self.hex(group["client_ephemeral_public_hex"] as! String),
        ])
        #expect(digest == Self.hex(group["digest_hex"] as! String))
    }

    @Test("A Keychain seed yields the same Ed25519 identity and signature as Rust")
    func ed25519MatchesRust() throws {
        let group = Self.group("ed25519")
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: Self.hex(group["seed_hex"] as! String))

        // CryptoKit's rawRepresentation is the seed, same as ed25519-dalek's
        // SigningKey::from_bytes. If that ever stopped holding, the app would
        // present a different identity than the CLI wrote to the Keychain.
        #expect(key.publicKey.rawRepresentation == Self.hex(group["public_key_hex"] as! String))

        let message = Data((group["message_utf8"] as! String).utf8)
        #expect(key.publicKey.isValidSignature(Self.hex(group["signature_hex"] as! String), for: message))
    }

    @Test("Client frames are byte-identical to the Rust SecureChannel")
    func channelEncryptionMatchesRust() throws {
        let group = Self.group("secure_channel")
        let channel = SecureChannel(
            sharedSecret: Self.hex(group["shared_secret_hex"] as! String),
            salt: Data((group["salt_utf8"] as! String).utf8),
            info: Data((group["info_utf8"] as! String).utf8)
        )
        for entry in group["client_to_server"] as! [[String: Any]] {
            let frame = try channel.encrypt(Data((entry["plaintext_utf8"] as! String).utf8))
            #expect(frame == Self.hex(entry["frame_hex"] as! String))
        }
    }

    @Test("Frames the daemon produced decrypt correctly, in order")
    func channelDecryptionMatchesRust() throws {
        let group = Self.group("secure_channel")
        let channel = SecureChannel(
            sharedSecret: Self.hex(group["shared_secret_hex"] as! String),
            salt: Data((group["salt_utf8"] as! String).utf8),
            info: Data((group["info_utf8"] as! String).utf8)
        )
        for entry in group["server_to_client"] as! [[String: Any]] {
            let plaintext = try channel.decrypt(Self.hex(entry["frame_hex"] as! String))
            #expect(String(decoding: plaintext, as: UTF8.self) == entry["plaintext_utf8"] as! String)
        }
    }

    @Test("A replayed frame is refused")
    func replayIsRefused() throws {
        let group = Self.group("secure_channel")
        let channel = SecureChannel(
            sharedSecret: Self.hex(group["shared_secret_hex"] as! String),
            salt: Data((group["salt_utf8"] as! String).utf8),
            info: Data((group["info_utf8"] as! String).utf8)
        )
        let frames = group["server_to_client"] as! [[String: Any]]
        let first = Self.hex(frames[0]["frame_hex"] as! String)
        _ = try channel.decrypt(first)
        // The receive counter has advanced, so the same frame no longer
        // authenticates under the expected nonce.
        #expect(throws: SecureChannel.Failure.self) { try channel.decrypt(first) }
    }

    @Test("A failed decrypt does not advance the receive counter")
    func failedDecryptDoesNotDesynchronise() throws {
        let group = Self.group("secure_channel")
        let channel = SecureChannel(
            sharedSecret: Self.hex(group["shared_secret_hex"] as! String),
            salt: Data((group["salt_utf8"] as! String).utf8),
            info: Data((group["info_utf8"] as! String).utf8)
        )
        let frames = group["server_to_client"] as! [[String: Any]]
        var tampered = Self.hex(frames[0]["frame_hex"] as! String)
        tampered[tampered.startIndex] ^= 0xFF
        #expect(throws: SecureChannel.Failure.self) { try channel.decrypt(tampered) }

        // The genuine first frame must still be readable.
        let plaintext = try channel.decrypt(Self.hex(frames[0]["frame_hex"] as! String))
        #expect(String(decoding: plaintext, as: UTF8.self) == frames[0]["plaintext_utf8"] as! String)
    }

    @Test("Base64url round-trips and rejects malformed input")
    func base64URLRoundTrips() {
        let raw = Data((0...255).map { UInt8($0 % 256) })
        let encoded = Base64URL.encode(raw)
        #expect(!encoded.contains("+") && !encoded.contains("/") && !encoded.contains("="))
        #expect(Base64URL.decode(encoded) == raw)
        #expect(Base64URL.decode("a") == nil)
    }
}
